### ISSUE TITLE
Spaces?

### ISSUE THREAD

**Issue by Deedasmi** [2016-ksu-cis-open-house/tree-display#4]
Should we allow spaces/special characters?

**Comment by kevindice** [comment]
Possibly and define "special characters."

We could just make it English only, but that might exclude lots of people.
Maybe we could find or implement a mapping from accented characters to
their boring analogs.  Ex. àáâãåā all map to 'a' and æ and ä map to 'ae'

**Comment by kevindice** [comment]
But you probably were talking about punctuation.  Maybe a hyphen is
necessary but nothing else comes to mind.

**Comment by Deedasmi** [comment]
My immediate concern is against the blacklist. I implemented it as a hashed set, which may not fit the use case well. If we just allow a-zA-Z, it would make the job a lot easier, both on the back end and to visualize.

**Comment by kevindice** [comment]
What if all capital letters were treated as lowercase letters for the
purpose of checking them against the white and black lists?  For
visualization, the ordering could also be case insensitive, but the display
could be the original string.

**Comment by Deedasmi** [comment]
The blacklist is currently implemented in a case-insensitive way. Everything on the list is lowered before being placed in the set, and everything checked against it is lowered. But still, being hashed, any spaces or extra letters at all wouldn't match. Since there will be a manual review process as well, I'm not sure if it's really a concern.
